### ISSUE TITLE
对战问题

### ISSUE THREAD

**Issue by zooeyQAQ** [sg-first/Military-chess-AI#1]
这个军旗算法 对战出现了 一直来回走卡死的情况 事算法本来就有这种问题吗

**Comment by sg-first** [comment]
是，[目前信息->最优解]这个函数掉到不动点附近了。你可以在外面判断一下，如果几次循环走就用一个固定策略打破

**Comment by zooeyQAQ** [comment]
感谢回复 哈哈哈


帮网店写好评20到30一单，每天300-500
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sg-first/Military-chess-AI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 凌晨1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sg-first/Military-chess-AI] 对战问题 (Issue #1)





 
是，[目前信息-&gt;最优解]这个函数掉到不动点附近了。你可以在外面判断一下，如果几次循环走就用一个固定策略打破
